name: docs

on:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # If you DON'T want docs to publish Pages (let the GDS viewer publish),
      # disable this job by gating it:
      # if: ${{ false }}

      - name: Build docs
        uses: TinyTapeout/tt-gds-action/docs@ttihp25b
