name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install simulator and Python deps
        run: |
          sudo apt-get update
          sudo apt-get install -y iverilog
          python -m pip install --upgrade pip
          pip install -r test/requirements.txt

      - name: Run cocotb via Makefile (Icarus)
        run: |
          make -C test SIM=icarus WAVES=1

      - name: Upload artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sim-artifacts
          path: |
            test/results.xml
            test/*.vcd
            test/sim_build/**/*.vcd
            test/sim_build/**/*.fst
          if-no-files-found: warn
